create schema if not exists private;
revoke all on schema private from public;

create type public.admin_role as enum ('owner', 'admin', 'editor', 'viewer');
create type public.lead_status as enum ('new', 'contacted', 'qualified', 'rejected', 'converted');

create table public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.admin_role not null default 'viewer',
  is_active boolean not null default true,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.content_documents (
  id uuid primary key default gen_random_uuid(),
  content_key text not null unique check (content_key ~ '^[a-z0-9][a-z0-9_-]{1,63}$'),
  draft_payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(draft_payload) = 'object' and pg_column_size(draft_payload) <= 1048576),
  version bigint not null default 1 check (version > 0),
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.published_content (
  content_key text primary key check (content_key ~ '^[a-z0-9][a-z0-9_-]{1,63}$'),
  payload jsonb not null
    check (jsonb_typeof(payload) = 'object' and pg_column_size(payload) <= 1048576),
  version bigint not null check (version > 0),
  published_at timestamptz not null default now()
);

create table public.content_revisions (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.content_documents(id) on delete cascade,
  version bigint not null check (version > 0),
  snapshot jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (document_id, version)
);

create table public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (length(action) between 3 and 80),
  entity_type text not null check (length(entity_type) between 2 and 80),
  entity_id text,
  metadata jsonb not null default '{}'::jsonb
    check (jsonb_typeof(metadata) = 'object' and pg_column_size(metadata) <= 65536),
  created_at timestamptz not null default now()
);

create table public.landing_leads (
  id uuid primary key default gen_random_uuid(),
  status public.lead_status not null default 'new',
  source text not null default 'landing' check (source in ('landing', 'manual')),
  name text not null check (length(name) between 1 and 160),
  contact text not null check (length(contact) between 3 and 320),
  event_type text,
  guest_range text,
  event_date date,
  message text check (message is null or length(message) <= 5000),
  catalog_selection_ids text[] not null default '{}'
    check (cardinality(catalog_selection_ids) <= 200),
  consent_version text not null,
  consented_at timestamptz not null,
  converted_project_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index landing_leads_status_created_idx on public.landing_leads (status, created_at desc);
create index content_revisions_document_created_idx on public.content_revisions (document_id, created_at desc);
create index admin_audit_log_actor_created_idx on public.admin_audit_log (actor_id, created_at desc);

create or replace function private.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function private.set_updated_at() from public;

create trigger admin_profiles_set_updated_at
before update on public.admin_profiles
for each row execute function private.set_updated_at();

create trigger content_documents_set_updated_at
before update on public.content_documents
for each row execute function private.set_updated_at();

create trigger landing_leads_set_updated_at
before update on public.landing_leads
for each row execute function private.set_updated_at();

create or replace function private.is_active_admin(allowed_roles public.admin_role[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_profiles profile
    where profile.id = (select auth.uid())
      and profile.is_active
      and profile.role = any(allowed_roles)
  );
$$;

revoke all on function private.is_active_admin(public.admin_role[]) from public;
grant usage on schema private to authenticated;
grant execute on function private.is_active_admin(public.admin_role[]) to authenticated;

alter table public.admin_profiles enable row level security;
alter table public.content_documents enable row level security;
alter table public.published_content enable row level security;
alter table public.content_revisions enable row level security;
alter table public.admin_audit_log enable row level security;
alter table public.landing_leads enable row level security;

revoke all on table public.admin_profiles from anon, authenticated;
revoke all on table public.content_documents from anon, authenticated;
revoke all on table public.published_content from anon, authenticated;
revoke all on table public.content_revisions from anon, authenticated;
revoke all on table public.admin_audit_log from anon, authenticated;
revoke all on table public.landing_leads from anon, authenticated;

grant select on table public.admin_profiles to authenticated;
grant select, insert, update on table public.content_documents to authenticated;
grant select on table public.published_content to anon, authenticated;
grant select on table public.content_revisions to authenticated;
grant select on table public.admin_audit_log to authenticated;
grant select, update on table public.landing_leads to authenticated;

create policy admin_profiles_read_self
on public.admin_profiles
for select
to authenticated
using ((select auth.uid()) = id);

create policy admin_profiles_read_for_admins
on public.admin_profiles
for select
to authenticated
using ((select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role])));

create policy content_documents_read
on public.content_documents
for select
to authenticated
using ((select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role, 'viewer'::public.admin_role])));

create policy content_documents_insert_with_mfa
on public.content_documents
for insert
to authenticated
with check (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and (select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role]))
  and updated_by = (select auth.uid())
);

create policy content_documents_update_with_mfa
on public.content_documents
for update
to authenticated
using (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and (select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role]))
)
with check (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and (select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role]))
  and updated_by = (select auth.uid())
);

create policy published_content_public_read
on public.published_content
for select
to anon, authenticated
using (true);

create policy content_revisions_read
on public.content_revisions
for select
to authenticated
using ((select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role, 'viewer'::public.admin_role])));

create policy admin_audit_log_read
on public.admin_audit_log
for select
to authenticated
using ((select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role])));

create policy landing_leads_read
on public.landing_leads
for select
to authenticated
using ((select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role, 'viewer'::public.admin_role])));

create policy landing_leads_update_with_mfa
on public.landing_leads
for update
to authenticated
using (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and (select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role]))
)
with check (
  (select auth.jwt() ->> 'aal') = 'aal2'
  and (select private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role]))
);

create or replace function public.publish_content(
  document_id uuid,
  expected_version bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  document public.content_documents%rowtype;
  next_version bigint;
begin
  if auth.uid() is null then
    raise exception 'authentication required' using errcode = '28000';
  end if;

  if coalesce(auth.jwt() ->> 'aal', 'aal1') <> 'aal2' then
    raise exception 'multi-factor authentication required' using errcode = '42501';
  end if;

  if not private.is_active_admin(array['owner'::public.admin_role, 'admin'::public.admin_role, 'editor'::public.admin_role]) then
    raise exception 'insufficient privileges' using errcode = '42501';
  end if;

  select * into document
  from public.content_documents
  where id = document_id
  for update;

  if not found then
    raise exception 'content document not found' using errcode = 'P0002';
  end if;

  if document.version <> expected_version then
    raise exception 'content version conflict' using errcode = '40001';
  end if;

  if document.draft_payload ->> 'version' <> '2' then
    raise exception 'unsupported content schema version' using errcode = '22023';
  end if;

  next_version := document.version + 1;

  update public.content_documents
  set version = next_version,
      updated_by = (select auth.uid())
  where id = document.id;

  insert into public.published_content (content_key, payload, version, published_at)
  values (document.content_key, document.draft_payload, next_version, now())
  on conflict (content_key) do update
  set payload = excluded.payload,
      version = excluded.version,
      published_at = excluded.published_at;

  insert into public.content_revisions (document_id, version, snapshot, created_by)
  values (document.id, next_version, document.draft_payload, (select auth.uid()));

  insert into public.admin_audit_log (actor_id, action, entity_type, entity_id, metadata)
  values (
    (select auth.uid()),
    'content.publish',
    'content_document',
    document.id::text,
    jsonb_build_object('content_key', document.content_key, 'version', next_version)
  );

  return next_version;
end;
$$;

revoke all on function public.publish_content(uuid, bigint) from public, anon;
grant execute on function public.publish_content(uuid, bigint) to authenticated;

comment on table public.published_content is 'Public read-only projection. Draft content never lives in this table.';
comment on table public.landing_leads is 'No anon INSERT grant by design. Leads must enter through a rate-limited server endpoint with anti-bot checks.';
comment on function public.publish_content(uuid, bigint) is 'Atomic MFA-protected publish with optimistic concurrency, revision snapshot, and audit event.';
